/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary": "#002e6a",
        "on-primary-container": "#00285d",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#222a3d",
        "on-secondary-container": "#d6a9ff",
        "surface-container-low": "#131b2e",
        "on-secondary-fixed-variant": "#6900b3",
        "surface-tint": "#adc6ff",
        "background": "#0b1326",
        "on-background": "#dae2fd",
        "surface-dim": "#0b1326",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-container": "#00311f",
        "surface-variant": "#2d3449",
        "surface-container": "#171f33",
        "secondary-fixed": "#f0dbff",
        "on-surface": "#dae2fd",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ddb7ff",
        "primary": "#adc6ff",
        "tertiary": "#4edea3",
        "surface": "#0b1326",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#6ffbbe",
        "primary-container": "#4d8eff",
        "outline": "#8c909f",
        "tertiary-container": "#00a572",
        "surface-container-lowest": "#060e20",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed-variant": "#004395",
        "inverse-surface": "#dae2fd",
        "error": "#ffb4ab",
        "on-primary-fixed": "#001a42",
        "inverse-on-surface": "#283044",
        "secondary-container": "#6f00be",
        "inverse-primary": "#005ac2",
        "on-secondary-fixed": "#2c0051",
        "outline-variant": "#424754",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#003824",
        "on-secondary": "#490080",
        "secondary": "#ddb7ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        "gutter": "24px",
        "unit": "4px"
      },
      "fontFamily": {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
